site_name: Hall thruster PEM
site_url: https://JANUS-Institute.github.io/HallThrusterPEM/
site_author: Joshua Eckels
repo_name: JANUS-Institute/HallThrusterPEM
repo_url: https://github.com/JANUS-Institute/HallThrusterPEM
copyright: Copyright &copy 2025 <a href="https://januselectricpropulsion.com/">JANUS Institute</a>
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src]

theme:
  name: material
  logo: assets/hallmd_logo.svg
  favicon: assets/hallmd_logo.svg
  palette:
    primary: cyan
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.instant
    - navigation.tabs       # Tab navigation at top of page
    - navigation.sections   # Extra layer in the left navigation panel
    - navigation.indexes    # Allow section titles to be clickable with an "index.md" file
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: sphinx
            docstring_section_style: spacy
            merge_init_into_class: true
            filters: [ "!^_" ]
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            group_by_category: true
            show_root_heading: true
            heading_level: 1
  - coverage:
      html_report_dir: htmlcov
  - git-committers:
      repository: JANUS-Institute/HallThrusterPEM
      branch: main
      exclude:
        - reference/*
        - abbreviations.md
        - coverage.md
        - changelog.md
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      exclude:
        - reference/*
        - abbreviations.md
        - coverage.md
        - changelog.md
  - markdown-exec
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - redirects:
      redirect_maps:
        index.md: start.md  # Force index page to be the "getting started" page, which is actually the README

nav:
  - Home:
      - Getting started: start.md
      - Tutorial: tutorial.md
      - Examples: examples.md
      - Contributing: contributing.md
      - Coverage report: coverage.md
      - Changelog: changelog.md
  - How-to Guides:
      - Load experimental data: guides/data.md
      - Run a Hall thruster model: guides/model.md
      - Build a surrogate: guides/surrogate.md
      - Calibrate a model: guides/calibrate.md
      - Validate a model: guides/validate.md
  - API reference: reference/  # literate-nav + gen-files
  - Theory:
      - Summary: theory/summary.md

exclude_docs: |
  abbreviations.md
  gen_ref_pages.py
  TODOC.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JANUS-Institute

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - styles/extra.css

markdown_extensions:
  - abbr                      # Abbreviations
  - admonition
  - attr_list                 # Add HTML/CSS attributes to markdown elements
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.snippets:
      dedent_subsections: true
      base_path: ['.', './src']
      auto_append:
        - docs/abbreviations.md
